
server:
  port: 4042

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true        		    
    
