
server:
  port: 4041

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training_dev
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: *
    endpoint:
      shutdown:
       enabled: true
    info:
      env:
        enabled: true
enpoints:
  shutdown:
    enabled: true
    
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
   name: account
   description: Account Microservice
   version: 1.0.0
