
server:
  port: 4043

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training_dev
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true        		    
    
